sudo: required
services:
  - docker

before_install:
  - docker build -t tragu/react-test -f ./client/Dockerfile.dev .
 
script:
  - docker run -e CI=true tragu/react-test npm test

after_success:
  - docker build -t tragu/multi-client ./client
  - docker build -t tragu/multi-nginx ./nginx
  - docker build -t tragu/multi-server ./server
  - docker build -t tragu/multi-worker ./worker
  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push tragu/multi-client
  - docker push tragu/multi-nginx
  - docker push tragu/multi-server
  - docker push tragu/multi-worker