sudo: required
services:
  - docker

before_install:
  - docker build -t tragu11/react-test -f ./client/Dockerfile.dev ./client
 
script:
  - docker run -e CI=true tragu11/react-test npm test

after_success:
  - docker build -t tragu11/multi-client ./client
  - docker build -t tragu11/multi-nginx ./nginx
  - docker build -t tragu11/multi-server ./server
  - docker build -t tragu11/multi-worker ./worker


  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push tragu11/multi-client:latest
  - docker push tragu11/multi-nginx:latest
  - docker push tragu11/multi-server:latest
  - docker push tragu11/multi-worker:latest
  # bruh